name: Publish Kiosk Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'rpi-kiosk/**'

jobs:
  build_and_publish:
    runs-on: [self-hosted, trusted]
    if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Kiosk image
        uses: docker/build-push-action@v6
        with:
          context: rpi-kiosk
          file: rpi-kiosk/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pantry-kiosk:latest
