name: Publish Kiosk Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'rpi-kiosk/**'

jobs:
  build_and_publish:
    runs-on: [self-hosted, trusted]
    if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.2

      - name: Install Arduino Core and Libs
        run: |
          arduino-cli config init --overwrite
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli lib install "HX711"

      - name: Compile Scale Firmware
        run: |
          arduino-cli compile --fqbn arduino:avr:uno --output-dir rpi-kiosk/arduino/scale/build rpi-kiosk/arduino/scale/scale.ino

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Kiosk image
        uses: docker/build-push-action@v6
        with:
          context: rpi-kiosk
          file: rpi-kiosk/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pantry-kiosk:latest
